ConnectionStrings:
  DefaultConnection: Server=localhost;Database=Konecta_Finance;Trusted_Connection=True;TrustServerCertificate=True;

RabbitMq:
  HostName: localhost
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  CompensationEventsQueue: finance.compensation.events
  CompensationProvisionedRoutingKey: finance.compensation.provisioned
  CompensationBonusesRoutingKey: finance.compensation.bonuses
  CompensationDeductionsRoutingKey: finance.compensation.deductions

Consul:
  Host: http://localhost:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://localhost:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: finance-service
  Host: host.docker.internal
  Port: 5003
  RegisterWithConsul: true
  FailFast: false
