ConnectionStrings:
  DefaultConnection: Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;

RabbitMq:
  HostName: rabbitmq
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  CompensationEventsQueue: finance.compensation.events
  CompensationProvisionedRoutingKey: finance.compensation.provisioned
  CompensationBonusesRoutingKey: finance.compensation.bonuses
  CompensationDeductionsRoutingKey: finance.compensation.deductions

Consul:
  Host: ${CONSUL_URI}

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://authentication-service:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: finance-service
  Host: 0.0.0.0
  PublicHost: finance-service
  Port: 5003
  RegisterWithConsul: true
  FailFast: false
