ConnectionStrings:
  DefaultConnection: ${FINANCE_DB_CONNECTION:Server=sqlserver,1433;Database=Konecta_Finance;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;}

RabbitMq:
  HostName: ${RABBITMQ_HOST:rabbitmq}
  Port: ${RABBITMQ_PORT:5672}
  UserName: ${RABBITMQ_USER:guest}
  Password: ${RABBITMQ_PASSWORD:guest}
  VirtualHost: ${RABBITMQ_VHOST:/}
  Exchange: konecta.erp
  CompensationEventsQueue: finance.compensation.events
  CompensationProvisionedRoutingKey: finance.compensation.provisioned
  CompensationBonusesRoutingKey: finance.compensation.bonuses
  CompensationDeductionsRoutingKey: finance.compensation.deductions

Consul:
  Host: ${CONSUL_ENDPOINT:http://consul:8500}

ServiceConfig:
  ServiceName: finance-service
  Host: 0.0.0.0
  Port: 5003
  RegisterWithConsul: true
  FailFast: false
