ConnectionStrings:
  DefaultConnection: Server=localhost;Database=Konecta_Hr;Trusted_Connection=True;TrustServerCertificate=True;
RabbitMq:
  HostName: localhost
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  FinanceCompensationProvisionedRoutingKey: finance.compensation.provisioned
  FinanceCompensationBonusesRoutingKey: finance.compensation.bonuses
  FinanceCompensationDeductionsRoutingKey: finance.compensation.deductions
  UserProvisionedQueue: hr.user-provisioned
  UserProvisionedRoutingKey: auth.user.provisioned

Consul:
  Host: http://localhost:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://localhost:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: hr-service
  Host: host.docker.internal
  Port: 5005
  RegisterWithConsul: true
  FailFast: false
