ConnectionStrings:
  DefaultConnection: ${HR_DB_CONNECTION:Server=sqlserver,1433;Database=Konecta_Hr;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;}

RabbitMq:
  HostName: ${RABBITMQ_HOST:rabbitmq}
  Port: ${RABBITMQ_PORT:5672}
  UserName: ${RABBITMQ_USER:guest}
  Password: ${RABBITMQ_PASSWORD:guest}
  VirtualHost: ${RABBITMQ_VHOST:/}
  Exchange: konecta.erp
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  FinanceCompensationProvisionedRoutingKey: finance.compensation.provisioned
  FinanceCompensationBonusesRoutingKey: finance.compensation.bonuses
  FinanceCompensationDeductionsRoutingKey: finance.compensation.deductions
  UserProvisionedQueue: hr.user-provisioned
  UserProvisionedRoutingKey: auth.user.provisioned

Consul:
  Host: ${CONSUL_ENDPOINT:http://consul:8500}

ServiceConfig:
  ServiceName: hr-service
  Host: 0.0.0.0
  Port: 5005
  RegisterWithConsul: true
  FailFast: false
