ConnectionStrings:
  DefaultConnection: Server=localhost;Database=Konecta_Inventory;Trusted_Connection=True;TrustServerCertificate=True;

Consul:
  Host: http://localhost:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://localhost:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: inventory-service
  Host: host.docker.internal
  Port: 5020
  RegisterWithConsul: true
  FailFast: false
