server:
  port: 8085

spring:
  application:
    name: reporting-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-${random.value}
        hostname: host.docker.internal
        prefer-ip-address: false
        health-check-path: /actuator/health
        health-check-interval: 15s
      config:
        enabled: false

services:
  finance:
    url: http://localhost:5003
  hr:
    url: http://localhost:5005
  inventory:
    url: http://localhost:5020

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
