ConnectionStrings:
  DefaultConnection: Server=localhost;Database=Konecta_UserManagement;Trusted_Connection=True;TrustServerCertificate=True;

RabbitMq:
  HostName: localhost
  Port: 5672
  UserName: guest
  Password: guest
  VirtualHost: /
  Exchange: konecta.erp
  UserEventsQueue: user-management.user-events
  UserProvisionedRoutingKey: auth.user.provisioned
  UserDeactivatedRoutingKey: auth.user.deactivated
  UserResignedRoutingKey: auth.user.resigned
  UserTerminatedRoutingKey: auth.user.terminated

Consul:
  Host: http://localhost:8500

JwtSettings:
  Issuer: KonectaERP
  Audience: KonectaERPUsers
  JwksUri: http://localhost:7280/.well-known/jwks.json
  RequireHttpsMetadata: false
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: user-management-service
  Host: host.docker.internal
  Port: 5078
  RegisterWithConsul: true
  FailFast: false
